stages:
  - deploy

image:
  name: ruby:3.1

push_to_github:
  stage: deploy

  script:
    - git clone https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@${GITHUB_URL} github-repo
    - cd github-repo
    - git checkout -b ${STAGING_BRANCH}
  rules:
    - if: $CI_COMMIT_BRANCH == "staging"